packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: "^6.0.3"
  valibot: "^1.4.2"

catalogs:
  tiptap:
    "@tiptap/core": "^3.27.1"
    "@tiptap/extension-image": "^3.27.1"
    "@tiptap/extension-link": "^3.27.1"
    "@tiptap/extension-text-align": "^3.27.1"
    "@tiptap/extension-underline": "^3.27.1"
    "@tiptap/extension-youtube": "^3.27.1"
    "@tiptap/html": "^3.27.1"
    "@tiptap/pm": "^3.27.1"
    "@tiptap/starter-kit": "^3.27.1"

engineStrict: true
resolutionMode: highest

allowBuilds:
  "@sentry/cli": true
  esbuild: true
