name: db backup
on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: execute remote script
        uses: appleboy/ssh-action@v1.2.5
        env:
          STORAGE_BUCKET_NAME: ${{ secrets.STORAGE_BUCKET_NAME }}
          STORAGE_ACCOUNT_ID: ${{ secrets.STORAGE_ACCOUNT_ID }}
          STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
          STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: STORAGE_BUCKET_NAME,STORAGE_ACCOUNT_ID,STORAGE_ACCESS_KEY_ID,STORAGE_SECRET_ACCESS_KEY
          script: |
            dbbackup
